{% set name = "pyre2" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6371a3494c33b74f4291aa755d6f50ebd78dc1d08e33e48f00c7517f60ef395

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cmake >=3.15
    - pybind11
    - ninja
    - cython
    - pip
    - re2
  run:
    - python
    - re2

test:
  imports:
    - re2
  source_files:
    - tests
  commands:
    - python -m unittest discover -f -s tests

about:
  home: "https://pypi.org/project/pyre2/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python wrapper for Google's RE2 using Cython"
  doc_url: "https://github.com/andreasvc/pyre2/blob/master/README.rst"
  dev_url: "https://github.com/andreasvc/pyre2"

extra:
  recipe-maintainers:
    - sarnold
