{% set name = "pyre2" %}
{% set version = "0.3.6" %}
{% set sha256 = "6a0a2c70b1ce98d870ce9423368cc83bbacc8a41f6e066296e197a26a842ede7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/andreasvc/pyre2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 10
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - ninja
    - cmake >=3.15
    - make                                   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - cython
    - pip
    - re2
  run:
    - python
    - re2

test:
  commands:
    - export "PYTHONIOENCODING=utf8"  # [unix]
    - set "PYTHONIOENCODING=utf8"  # [win]
    - python -m unittest discover -f -s tests
  imports:
    - re2
  source_files:
    - tests

about:
  home: https://pypi.org/project/pyre2/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for Google's RE2 using Cython
  doc_url: https://github.com/andreasvc/pyre2/blob/master/README.rst
  dev_url: https://github.com/andreasvc/pyre2

extra:
  recipe-maintainers:
    - sarnold
