{% set name = "pyre2" %}
{% set version = "0.3.6" %}
{% set sha256 = "2115d325b2793e85a6a488af9c6de5efbb5f850157b613a9245b791da436a318" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/andreasvc/pyre2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cmake >=3.15
    - pybind11
    - ninja
    - cython
    - pip
    - re2
  run:
    - python
    - re2

test:
  commands:
    - export "PYTHONIOENCODING=utf8"  # [unix]
    - set "PYTHONIOENCODING=utf8"  # [win]
    - python -m unittest discover -f -s tests
  imports:
    - re2
  source_files:
    - tests

about:
  home: https://pypi.org/project/pyre2/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for Google's RE2 using Cython
  doc_url: https://github.com/andreasvc/pyre2/blob/master/README.rst
  dev_url: https://github.com/andreasvc/pyre2

extra:
  recipe-maintainers:
    - sarnold
